name: FOBA
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07846
title: Fair Oaks Beautification Association
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2f3a50'
    - '#ad9d91'
    - '#a9d2f0'
    - '#c15e3c'
  brandStrength: 0.5182602230925113
  lightness: 1
  saturation: 0.7274568360298872
  rhythmicContrast: 0.9350588775705546
purpose: []
